name: USYD-HCI-Summer-School
remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

defaults:
  author_profile: true
