name: USYD-HCI-Summer-School
remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache


defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      author_profile: true

author:
  name: "The University of Sydney"
  avatar: "/assets/logo/logo.png"
